server:
  port: 8084
spring:
  main:
    web-application-type: reactive
  application:
    name: shop-service
  data:
    redis:
      port: 6379
      host: 127.0.0.1
  config:
    import:
      - 'classpath:config/liquibase.yml'
      - 'classpath:config/r2dbc.yml'
      - 'classpath:config/oauth2.yml'
      - 'classpath:config/eureka-client.yml'
      - 'classpath:config/springdoc.yml'
      - 'classpath:config/debezium.yml'
      - 'classpath:management.yml'

vnpay:
  tmn-code: ${VNPAY_TMN_CODE:BE8FM4RD}
  hash-secret: ${VNPAY_HASH_SECRET:IN8YPAORH1GN423KCYKTW1UGE61KIYBR}
  url: ${VNPAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
  return-url: ${VNPAY_RETURN_URL:https://api.thaiha.website/shop-service/v1/payment/vnpay-return}

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: DEBUG