server:
  port: 9000

auth:
  issuer-uri: ${AUTH_ISSUER_URI:http://127.0.0.1:9000}

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5432}/${DB_SCHEMA:authentication}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://127.0.0.1:8761/eureka}
  instance:
    prefer-ip-address: true

client:
  workflow-service:
    url: ${WORKFLOW_SERVICE:http://127.0.0.1:8080}

ldap:
  url: ldap://localhost:389
  base: dc=mycompany,dc=local
  username: cn=admin,dc=mycompany,dc=local
  password: admin_secret
  user-search-base: ou=users
  user-search-filter: "(cn={0})"
  group-search-base: ou=groups

management:
  health:
    redis:
      enabled: false
    ldap:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    org.springframework.web: ${LOGGING_LEVEL_SPRING_WEB:INFO}
    org.springframework.security: ${LOGGING_LEVEL_SPRING_SECURITY:DEBUG}
    org.springframework.security.oauth2: ${LOGGING_LEVEL_SPRING_OAUTH2:DEBUG}
    org.springframework.security.web.FilterChainProxy: INFO

