spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:127.0.0.1:29092}
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.takypok.workflowservice.model.event
        spring.json.value.default.type: com.takypok.workflowservice.model.event.EmployeeEvent
        spring.json.use.type.headers: false

employee-events:
  topic: employee.events
