server:
  port: 8082
spring:
  main:
    web-application-type: reactive
  application:
    name: media-service
  config:
    import:
      - 'classpath:config/liquibase.yml'
      - 'classpath:config/r2dbc.yml'
      - 'classpath:config/oauth2.yml'
      - 'classpath:config/eureka-client.yml'
      - 'classpath:config/springdoc.yml'
      - 'classpath:management.yml'
  codec:
    max-in-memory-size: 512MB
  webflux:
    multipart:
      max-in-memory-size: 512MB
      max-disk-usage-per-part: -1

management:
  endpoint:
    health:
      show-details: always

storage:
  base-dir: ./storage
  raw-dir: ./storage/raw
  hls-dir: ./storage/hls

ffmpeg:
  path: ""
  cache-dir: ~/.cache/media-service/ffmpeg
  download-timeout-seconds: 120

logging:
  config: classpath:log4j2-spring.xml
  level:
    root: INFO
    io.r2dbc.postgresql.QUERY: INFO
    io.r2dbc.postgresql.PARAM: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: DEBUG
