services:
  auth-service:
    build:
      context: ..
      dockerfile: auth-service/Dockerfile
    container_name: auth-service
    ports:
      - "9000:9000"
    environment:
      AUTH_ISSUER_URI: http://192.168.1.16:9000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_SCHEMA: authentication
      DB_USER: postgres
      DB_PASSWORD: postgres
      EUREKA_URI: http://discovery-service:8761/eureka
      LDAP_URL: ${LDAP_URL}
      LDAP_BASE: ${LDAP_BASE}
      LDAP_USERNAME: ${LDAP_USERNAME}
      LDAP_PASSWORD: ${LDAP_PASSWORD}
      LDAP_USER_SEARCH_BASE: ${LDAP_USER_SEARCH_BASE}
      LDAP_USER_SEARCH_FILTER: ${LDAP_USER_SEARCH_FILTER}
      LDAP_GROUP_SEARCH_BASE: ${LDAP_GROUP_SEARCH_BASE}
    depends_on:
      postgres:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    logging:
      driver: json-file
      options:
        max-size: "500m"
        max-file: "1"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

