services:
  auth-service:
    build:
      context: ..
      dockerfile: auth-service/Dockerfile
    image: takypok/auth-service
    container_name: auth-service
    ports:
      - "9000:9000"
    environment:
      AUTH_ISSUER_URI: ${AUTH_ISSUER_URI:-http://192.168.1.5:9000}
      DB_HOST: ${DB_HOST:-postgres}
      DB_PORT: ${DB_PORT:-5432}
      DB_SCHEMA: authentication
      DB_USER: postgres
      DB_PASSWORD: postgres
      SPRING_DATA_REDIS_HOST: ${SPRING_DATA_REDIS_HOST:-redis}
      SPRING_DATA_REDIS_PORT: ${SPRING_DATA_REDIS_PORT:-6379}
      EUREKA_URI: ${EUREKA_URI:-http://discovery-service:8761/eureka}
      LDAP_URL: ${LDAP_URL:-ldap://host.docker.internal:389}
      LDAP_BASE: dc=mycompany,dc=local
      LDAP_USERNAME: cn=admin,dc=mycompany,dc=local
      LDAP_PASSWORD: admin_secret
      LDAP_USER_SEARCH_BASE: ou=users
      LDAP_USER_SEARCH_FILTER: "(cn={0})"
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS:-kafka:9092}
      MANAGEMENT_OTLP_TRACING_ENDPOINT: ${MANAGEMENT_OTLP_TRACING_ENDPOINT:-http://tempo:4318/v1/traces}
      WORKFLOW_REDIRECT_URIS: ${WORKFLOW_REDIRECT_URIS:-http://localhost:3000/callback,https://app.thaiha.website/callback,https://oauth.pstmn.io/v1/callback,com.takypok.workflow://oauth2redirect}
      WORKFLOW_POST_LOGOUT_REDIRECT_URIS: ${WORKFLOW_POST_LOGOUT_REDIRECT_URIS:-http://localhost:3000/login,https://app.thaiha.website/login}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      discovery-service:
        condition: service_healthy
    networks:
      - takypok_default
    logging:
      driver: json-file
      options:
        max-size: "500m"
        max-file: "1"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  takypok_default:
    external: true

