services:
  media-service:
    build:
      context: ..
      dockerfile: media-service/Dockerfile
    container_name: media-service
    ports:
      - "8082:8082"
    environment:
      AUTH_ISSUER_URI: http://192.168.1.16:9000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_SCHEMA: media
      DB_USER: postgres
      DB_PASSWORD: postgres
      EUREKA_URI: http://discovery-service:8761/eureka
      JWK_URI: http://auth-service:9000/oauth2/jwks
    depends_on:
      postgres:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    logging:
      driver: json-file
      options:
        max-size: "500m"
        max-file: "1"
    restart: on-failure

