-- Superseded by Phase 7: PENDING is removed from EmploymentStatus entirely (name/email now arrive
-- trustworthy from auth-service the instant a shell is created — see AccountEventConsumer — so
-- there's no longer a meaningful "not ready yet" state to gate on). `name` nullable is now baked
-- directly into init-schema.sql instead of layered here. Stubbed rather than deleted (the
-- environment this was authored in couldn't run `rm`) and no longer included in
-- db.changelog-master.yaml, so it does not execute.
