services:
  gateway-service:
    build:
      context: ..
      dockerfile: gateway-service/Dockerfile
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      AUTH_ISSUER_URI: http://192.168.1.16:9000
      EUREKA_URI: http://discovery-service:8761/eureka
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      discovery-service:
        condition: service_healthy
    logging:
      driver: json-file
      options:
        max-size: "500m"
        max-file: "1"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3