server:
  port: 8083

spring:
  application:
    name: chat-service

  mvc:
    servlet:
      path: /chat
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen2.5:7b-instruct-q4_K_M
        options:
          temperature: 0.1        # low = more factual, less creative
          num-ctx: 4096           # context window size
      embedding:
        model: bge-m3
    vectorstore:
      qdrant:
        host: localhost
        port: 6334
        collection-name: crm_vi
        initialize-schema: true   # auto-creates collection on first run

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://127.0.0.1:8761/eureka}
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.ai: DEBUG