pipeline {
    agent any
    stages {
        stage('SSH to Postgres') {
            steps {
                sshagent(credentials: ['server-db-credentials']) {
                    sh '''
                        ssh -o StrictHostKeyChecking=no \
                            thaiha@192.168.147.107 \
                            'echo Hello from Server B'
                    '''
                }
            }
        }
    }
}
